[experiment]
name = "mlp-city-center-v1-learning-rates"
seed = 727
dataset = "data/processed/legacy.csv"
features = ["distance_km",  "review_scores_rating", "number_of_reviews"]
target = "price"

[data_split] # Has to add up to one
train = 0.7
validation = 0.1
test = 0.2

[preprocessing]
version = "v1"
imputer = "constant"
fill_value = 0

[training]
model = ["mlp"]
optimizer = ["adam"]
loss_fn = ["mse"]
epochs = [25]
lr = [0.0001, 0.001, 0.01, 0.1, 1, 10]
batch_size = [64]
